services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@test-db:5432/postgres

    depends_on:
      - test-db

  test-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
